    def sel_():
        
        s = CTkFrame(sct,border_width=3)
        s.pack(pady=3,anchor=E)
        s.grid_columnconfigure([0,1],weight=1)
        s.grid_rowconfigure([0],weight=1)
        ent_id = CTkEntry(s,63,28,0,font=CTkFont('Vazir',11))
        ent_id.insert(END,'شماره پذیرش')
        ent_id.grid(row=0,column=10,sticky=E)
        ent_sys = CTkEntry(s,corner_radius=0,font=font_enry,justify=CENTER)
        ent_sys.insert(END,"مالک دستگاه")
        ent_sys.grid(row=0,column=9,sticky=E,)
        ent_sys_type = CTkEntry(s,corner_radius=0,font=font_enry,justify=CENTER)
        ent_sys_type.insert(END,"نام دستگاه")
        ent_sys_type.grid(row=0,column=8,sticky=E,)
        ent_sys_model = CTkEntry(s,corner_radius=0,font=font_enry,justify=CENTER)
        ent_sys_model.insert(END,"مدل دستگاه")
        ent_sys_model.grid(row=0,column=7,sticky=E,)
        ent_sys_serial = CTkEntry(s,corner_radius=0,font=font_enry,justify=CENTER)
        ent_sys_serial.insert(END,"کدملی")
        ent_sys_serial.grid(row=0,column=6,sticky=E,)
        ent_sys_war = CTkEntry(s,corner_radius=0,font=font_enry,justify=CENTER)
        ent_sys_war.insert(END,"موبایل")
        ent_sys_war.grid(row=0,column=5,sticky=E,)
        list_sel = [ent_id,ent_sys,ent_sys_type,ent_sys_model,ent_sys_serial,ent_sys_war,]
        for sell in list_sel:
            sell.configure(state=DISABLED)  
        con = sqlite3.connect("pz.db")
        c = con.cursor()
        list_id = []
        for row in c.execute('SELECT * FROM paziresh WHERE status=0'):
            list_id.append(row[0])
            a=row[0]+1590
            s = CTkFrame(sct,border_width=3,fg_color='blue')
            s.pack(pady=3,anchor=E)
            s.grid_columnconfigure([0,1],weight=1)
            s.grid_rowconfigure([0],weight=1)
            ent_id = CTkEntry(s,63,font=font_enry)
            ent_id.insert(END,a)
            ent_id.grid(row=0,column=10,sticky=E)
            ent_sys = CTkEntry(s,font=font_enry,justify=RIGHT)
            ent_sys.insert(END,row[7])
            ent_sys.grid(row=0,column=9,sticky=E,)
            ent_sys_type = CTkEntry(s,font=font_enry,justify=RIGHT)
            ent_sys_type.insert(END,row[3])
            ent_sys_type.grid(row=0,column=8,sticky=E,)
            ent_sys_model = CTkEntry(s,font=font_enry,justify=RIGHT)
            ent_sys_model.insert(END,row[5])
            ent_sys_model.grid(row=0,column=7,sticky=E,)
            ent_sys_serial = CTkEntry(s,font=font_enry,justify=RIGHT)
            n = f"0{row[9]}"
            ent_sys_serial.insert(END,n)
            ent_sys_serial.grid(row=0,column=6,sticky=E,)
            ent_sys_war = CTkEntry(s,font=font_enry,justify=RIGHT)
            f = f"0{row[8]}"
            ent_sys_war.insert(END,f)
            ent_sys_war.grid(row=0,column=5,sticky=E,)
            
            list_sel = [ent_id,ent_sys,ent_sys_type,ent_sys_model,ent_sys_serial,ent_sys_war,]
            for sel in list_sel:
                sel.configure(state=DISABLED)
            
            def pr():
                for j in list_id:
                    print(j)
                    show(row[0])
            btn_show = CTkButton(s,font=font,text='Show',command=pr)
            btn_show.grid(row=0,column=4,sticky=E,)
        con.commit()
        con.close()
        
        def show(data):
    con = sqlite3.connect("pz.db")
    c = con.cursor()
    for i in c.execute(f'SELECT * FROM paziresh WHERE id={data}'):
        f_show = CTkFrame(root)
        f_show.grid(row=1, column=0,rowspan=7, sticky=NSEW)    
        f_show.grid_columnconfigure((0,1,2,3,4,5), weight=1)
        f_show.grid_rowconfigure((0, 1, 2, 3), weight=1)
        f_show.grid_rowconfigure((4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15,), weight=1)
        bt_back = customtkinter.CTkButton(f_show, text="بازگشت",font=font, fg_color= '#EA0000', hover_color = '#B20000', command=dashbord)
        bt_back.grid(row=13, column=0, padx=20, pady=(10, 0),sticky=E)

        bt_save = customtkinter.CTkButton(f_show, text="ذخیره",font=font,fg_color="green",hover_color="#00ff00",)
        bt_save.grid(row=13, column=1, padx=20, pady=(10, 0),)
        
        bt_save = customtkinter.CTkButton(f_show, text="ذخیره و پرینت",font=font,fg_color="green",hover_color="#00ff00",)
        bt_save.grid(row=13, column=2, padx=20, pady=(10, 0),sticky=W)
        
        lbl_id = CTkLabel(f_show, font=font,text=": شماره پذریش ")
        lbl_id.grid(row=0, column=5,pady=5)
        lbl_1 = CTkLabel(f_show, text="مشخصات دستگاه",font=font,corner_radius=20)
        lbl_1.grid(row=1,column=5,sticky=E,padx=10,pady=5)
        ent_input_id = CTkEntry(f_show,font=font_enry,justify=RIGHT)
        ent_input_id.grid(row=0, column=4)
        a = i[0]+1590
        ent_input_id.insert(0,a)
        ent_input_id.configure(state=DISABLED)
        
        lbl_date_of_arrival = CTkLabel(f_show, font=font,text=" : تاریخ ورود")
        lbl_date_of_arrival.grid(row=0, column=3,pady=5)
        ent_date_of_arrival = CTkEntry(f_show,font=font_enry,justify=RIGHT)
        ent_date_of_arrival.grid(row=0, column=2,pady=5)
        ent_date_of_arrival.insert(0,i[1])
        lbl_departure_date = CTkLabel(f_show, font=font,text=" : تاریخ خروج")
        lbl_departure_date.grid(row=0, column=1,pady=5)
        
        
        ent_departure_date = CTkEntry(f_show,font=font_enry)
        ent_departure_date.grid(row=0, column=0,pady=5)
        #########################################################################################
        frame_top = CTkFrame(f_show)
        frame_top.grid(row=2,column=0,columnspan=6,rowspan=3,sticky=NSEW) 
        frame_top.grid_columnconfigure((0,1,2,3,4,5),weight=1)
        frame_top.grid_rowconfigure((0,1),weight=1)
        lbl_input_system = CTkLabel(frame_top,text=" : نام دستگاه",font=font)
        lbl_input_system.grid(row=0,column=5)
        ent_input_system = CTkEntry(frame_top,font=font,justify=RIGHT)
        ent_input_system.insert(0,i[3])
        ent_input_system.grid(row=0,column=4)
        lbl_input_system_type = CTkLabel(frame_top,text=" : نوع دستگاه",font=font)
        lbl_input_system_type.grid(row=0,column=3)
        tv_list = [i[4]]
        combo_input_system_type = CTkComboBox(frame_top,font=font_enry,values=tv_list)
        combo_input_system_type.grid(row=0,column=2)
        lbl_input_system_model = CTkLabel(frame_top,text=" : مدل دستگاه",font=font)
        lbl_input_system_model.grid(row=0,column=1)
        ent_input_system_model = CTkEntry(frame_top,font=font,justify=RIGHT)
        ent_input_system_model.insert(0,i[5])
        ent_input_system_model.grid(row=0,column=0)
        lbl_input_system_serial = CTkLabel(frame_top,text=" : سریال دستگاه",font=font)
        lbl_input_system_serial.grid(row=1,column=5)
        ent_input_system_serial = CTkEntry(frame_top,font=font,justify=RIGHT)
        ent_input_system_serial.insert(0,i[6])
        ent_input_system_serial.grid(row=1,column=4)
        #########################################################################
        lbl_2 = CTkLabel(f_show, text="مشخصات مالک",font=font)
        lbl_2.grid(row=5,column=5,sticky=E,padx=10)
        frame_down = CTkFrame(f_show,)
        frame_down.grid(row=6,column=0,columnspan=6,rowspan=3,sticky=NSEW) 
        frame_down.grid_columnconfigure((0,1,2,3,4,5),weight=1)
        frame_down.grid_rowconfigure((0,1),weight=1)
        lbl_input_name = CTkLabel(frame_down,text=" : نام مالک",font=font)
        lbl_input_name.grid(row=0,column=5)
        ent_input_name = CTkEntry(frame_down,font=font_enry,justify=RIGHT)
        ent_input_name.insert(0,i[7])
        ent_input_name.grid(row=0,column=4)
        lbl_input_name_tel = CTkLabel(frame_down,text=" : شماره تلفن",font=font)
        lbl_input_name_tel.grid(row=0,column=3)
        ent_input_name_tel = CTkEntry(frame_down,font=font_enry,justify=LEFT)
        ent_input_name_tel.insert(0,i[8])
        ent_input_name_tel.grid(row=0,column=2)
        lbl_input_name_code_meli = CTkLabel(frame_down,text=" : کد ملی ",font=font)
        lbl_input_name_code_meli.grid(row=0,column=1)
        ent_input_name_code_meli = CTkEntry(frame_down,font=font_enry,justify=LEFT)
        ent_input_name_code_meli.insert(0,i[9])
        ent_input_name_code_meli.grid(row=0,column=0)
        lbl_input_name_tel_sabet = CTkLabel(frame_down,text=" : تلفن ثابت",font=font)
        lbl_input_name_tel_sabet.grid(row=1,column=5)
        ent_input_name_tel_sabet = CTkEntry(frame_down,font=font_enry,justify=RIGHT)
        ent_input_name_tel_sabet.insert(0,i[10])
        ent_input_name_tel_sabet.grid(row=1,column=4)
        lbl_input_name_adress = CTkLabel(frame_down,text=" : آدرس ",font=font)
        lbl_input_name_adress.grid(row=1,column=3)
        ent_input_name_adress = CTkTextbox(frame_down,font=font,corner_radius=10,width=600,border_width=3)
        ent_input_name_adress.tag_config("rtl",justify=RIGHT)
        ent_input_name_adress.tag_add("rtl",0.0,END)
        ent_input_name_adress.insert(0.0,i[11],'rtl')
        ent_input_name_adress.grid(row=1,column=0,columnspan=2,)
        #############################################################################
        lbl_3 = CTkLabel(f_show, text="مشخصات مشکل",font=font)
        lbl_3.grid(row=9,column=5,sticky=E,padx=10)
        frame_moshkel = CTkFrame(f_show)
        frame_moshkel.grid(row=10,column=0,columnspan=6,rowspan=3,sticky=NSEW) 
        frame_moshkel.grid_columnconfigure((0,1,2,3,4),weight=1)
        frame_moshkel.grid_rowconfigure((0,1,2),weight=1)
        lbl_problem = CTkLabel(frame_moshkel,text=' : ایراد ظاهری',font=font)
        lbl_problem.grid(row=0,column=3,)
        ent_problem = CTkTextbox(frame_moshkel,font=font_enry,corner_radius=10,width=500,height=120,border_width=3)
        ent_problem.grid(row=0,column=2,sticky=E)
        ent_problem.tag_config('rtl',justify=RIGHT)
        ent_problem.tag_add('rtl',0.0,END)
        ent_problem.insert(0.0,i[12],'rtl')
        lbl_cost = CTkLabel(frame_moshkel,text=' : هزینه ',font=font)
        lbl_cost.grid(row=0,column=1,sticky=E)
        ent_cost = CTkEntry(frame_moshkel,font=font_enry,justify=RIGHT)
        ent_cost.grid(row=0,column=0,sticky=E)
        ent_cost.insert(0,i[13])
        lbl_input_description = CTkLabel(frame_moshkel,text=" : توضیحات ",font=font)
        lbl_input_description.grid(row=1,column=3)
        ent_input_description = CTkTextbox(frame_moshkel,font=font_enry,corner_radius=10,width=500,height=120,border_width=3)
        ent_input_description.tag_config("rtl",justify=RIGHT)
        ent_input_description.tag_add("rtl",0.0,END)
        ent_input_description.insert(0.0,i[14],'rtl')
        ent_input_description.grid(row=1,column=2,sticky=E)
        lbl_tak = CTkLabel(frame_moshkel,text=": نظر تکنسین",font=font)
        lbl_tak.grid(row=2,column=3)
        ent_tak = CTkTextbox(frame_moshkel,font=font_enry,corner_radius=10,width=500,height=120,border_width=3)
        ent_tak.tag_config("rtl",justify=RIGHT)
        ent_tak.tag_add("rtl",0.0,END)
        ent_tak.insert(0.0,i[17],'rtl')
        ent_tak.grid(row=2,column=2,sticky=E,)
        lbl_chek = CTkLabel(frame_moshkel,0,28,font=font,text="آیاگارانتی دارد؟")
        lbl_chek.grid(row=1,column=1,sticky=E)
        lbl_modat_garanti =CTkLabel(frame_moshkel,font=font,text="مدت گارنتی",)
        lbl_modat_garanti.grid(row=2,column=1,sticky=NE,)
        ent_modat_garanti =CTkEntry(frame_moshkel,placeholder_text="مدت گارانتی",font=font_enry,justify=CENTER,)
        
        ent_modat_garanti.insert(0,i[16])
        ent_modat_garanti.grid(row=2,column=1,sticky=E,)
        def modat():
            if chek.get() == "بلی":
                ent_modat_garanti.configure(state=NORMAL)
            elif chek.get() == "خیر":
                ent_modat_garanti.configure(state=DISABLED)
        def exittt():
            if chek_exit.get() == 1:
                ent_departure_date.insert(0,JalaliDate.today().strftime('%Y/%m/%d'))
                ent_departure_date.configure(state=DISABLED)
        b = int(i[18])
        val = IntVar(value=b)
        chek_exit = CTkCheckBox(frame_moshkel,text="خروجی از سامانه",font=font,onvalue=1,variable=val,offvalue=0,command=exittt)
        chek_exit.grid(row=2,column=0,sticky=E)
        
        abbbb = f'{i[15]}'
        str_ = StringVar(value=abbbb)
        chek = CTkCheckBox(frame_moshkel,70,text="بلی",font=font,onvalue="بلی",offvalue="خیر",variable=str_,command=modat)
        chek.grid(row=1,column=1,sticky=W)
        chek_2 = CTkCheckBox(frame_moshkel,text="خیر",font=font,onvalue="خیر",offvalue="بلی",variable=str_,command=modat)
        chek_2.grid(row=1,column=0,sticky=E)
        def exitt():
            if chek_exit.get() == 1:
                ent_departure_date.insert(0,JalaliDate.today().strftime('%Y/%m/%d'))
                ent_departure_date.configure(state=DISABLED)
        exitt()